# Generated by Django 3.0.3 on 2020-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200519_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=13838500, max_length=20),
        ),
    ]
