# Generated by Django 3.0.3 on 2020-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20200523_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='authy_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=99749129, max_length=20),
        ),
    ]
