# Generated by Django 3.0.3 on 2020-05-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20200526_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=20898864, max_length=20),
        ),
    ]
