# Generated by Django 3.0.3 on 2020-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20200529_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=73046522, max_length=20),
        ),
    ]
