# Generated by Django 3.0.3 on 2020-05-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20200529_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=56999849, max_length=20),
        ),
    ]
