# Generated by Django 3.0.3 on 2020-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20200531_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=53321912, max_length=20),
        ),
    ]
