# Generated by Django 3.0.3 on 2020-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20200601_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=70011812, max_length=20),
        ),
    ]
