# Generated by Django 3.0.3 on 2020-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_auto_20200601_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=54559030, max_length=20),
        ),
    ]
