# Generated by Django 3.0.3 on 2020-06-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_auto_20200613_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=61237792, max_length=20),
        ),
    ]
