# Generated by Django 3.0.3 on 2020-06-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_auto_20200613_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_id',
            field=models.CharField(default=29036454, max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Role'),
        ),
    ]
