# Generated by Django 3.0.3 on 2020-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='email_preference',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_content',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='content_1',
            field=models.TextField(blank=True, max_length=65500, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='content_2',
            field=models.TextField(blank=True, max_length=65500, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='content_3',
            field=models.TextField(blank=True, max_length=65500, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='content_4',
            field=models.TextField(blank=True, max_length=65500, null=True),
        ),
    ]
