# Generated by Django 3.0.3 on 2020-05-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200519_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=77259112),
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_title', models.CharField(max_length=250)),
                ('filter_value', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Products')),
            ],
            options={
                'verbose_name_plural': 'ProductFilter',
            },
        ),
    ]
