# Generated by Django 3.0.3 on 2020-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200519_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='model_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=55291734),
        ),
    ]
