# Generated by Django 3.0.3 on 2020-05-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20200523_0647'),
        ('products', '0007_auto_20200519_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.State'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='lattitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=97229136),
        ),
    ]
