# Generated by Django 3.0.3 on 2020-05-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20200524_1234'),
        ('products', '0009_auto_20200524_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_section',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=27591856),
        ),
        migrations.CreateModel(
            name='ProductPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_after_tax', models.FloatField(default=0.0)),
                ('total_products_price', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.OrderId')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ProductsPaymentMethod')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.ProductReward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Register')),
            ],
        ),
    ]
