# Generated by Django 3.0.3 on 2020-05-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200525_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='longitude',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=93447615),
        ),
    ]
