# Generated by Django 3.0.3 on 2020-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200525_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=44767233),
        ),
        migrations.AlterField(
            model_name='products',
            name='delivery_charges',
            field=models.FloatField(default=0.0),
        ),
    ]
