# Generated by Django 3.0.3 on 2020-05-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200525_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=43110466),
        ),
    ]
