# Generated by Django 3.0.3 on 2020-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200527_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=97877938),
        ),
    ]
