# Generated by Django 3.0.3 on 2020-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200527_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='is_trading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=16048028),
        ),
    ]
