# Generated by Django 3.0.3 on 2020-05-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200527_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=90322879),
        ),
        migrations.AlterField(
            model_name='products',
            name='in_offer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
