# Generated by Django 3.0.3 on 2020-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200527_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=18576251),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(default='products', max_length=255),
        ),
    ]
