# Generated by Django 3.0.3 on 2020-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200527_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sub_id',
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=81726483),
        ),
    ]
