# Generated by Django 3.0.3 on 2020-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200529_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=72480064),
        ),
    ]
