# Generated by Django 3.0.3 on 2020-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200529_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspec',
            name='second_description',
            field=models.TextField(default=None, max_length=20000),
        ),
        migrations.AddField(
            model_name='productspec',
            name='second_title',
            field=models.CharField(choices=[('Technical Specification', 'Technical Specification'), ('General Specification', 'General Specification'), ('Design Specification', 'Design Specification')], default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='productspec',
            name='third_description',
            field=models.TextField(default=None, max_length=20000),
        ),
        migrations.AddField(
            model_name='productspec',
            name='third_title',
            field=models.CharField(choices=[('Technical Specification', 'Technical Specification'), ('General Specification', 'General Specification'), ('Design Specification', 'Design Specification')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=18503868),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='title',
            field=models.CharField(choices=[('Technical Specification', 'Technical Specification'), ('General Specification', 'General Specification'), ('Design Specification', 'Design Specification')], default=None, max_length=200),
        ),
    ]
