# Generated by Django 3.0.3 on 2020-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200531_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=33157167),
        ),
    ]
