# Generated by Django 3.0.3 on 2020-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200531_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=87813934),
        ),
    ]
