# Generated by Django 3.0.3 on 2020-06-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_auto_20200601_1426'),
        ('products', '0030_auto_20200601_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_amount', models.FloatField(default=0.0)),
                ('delivery_date_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('Your Order Has Placed', 'Your Order Has Placed'), ('Order Shipped', 'Order Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Your Order Has Placed', max_length=200)),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OTPHistory',
        ),
        migrations.RemoveField(
            model_name='productreward',
            name='order',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cancellation_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpayments',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=49566771),
        ),
        migrations.AlterField(
            model_name='productreward',
            name='reward_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rewardredeem',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderproductdeliver',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.OrderId'),
        ),
        migrations.AddField(
            model_name='orderproductdeliver',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.OrderProduct'),
        ),
        migrations.AddField(
            model_name='orderproductdeliver',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Products'),
        ),
        migrations.AddField(
            model_name='orderproductdeliver',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.Register'),
        ),
    ]
