# Generated by Django 3.0.3 on 2020-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200601_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_cancel_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=27696758),
        ),
    ]
