# Generated by Django 3.0.3 on 2020-06-02 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20200601_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductdeliver',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.ProductsPaymentMethod'),
        ),
        migrations.AddField(
            model_name='orderproductdeliver',
            name='payment_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderproductdeliver',
            name='product_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orderid',
            name='order_id',
            field=models.IntegerField(default=54341036),
        ),
    ]
